version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  am-analytics:
    image: wso2/wso2am-analytics-worker:2.6.0
    ports:
      - "9091:9091"
      - "9444:9444"
      - "7444:7444"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9091"]
      interval: 10s
      timeout: 120s
      start_period: 120s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apim-analytics:/home/wso2carbon/wso2-config-volume
  api-manager:
    image: wso2/wso2am:2.6.0
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
    volumes:
      - ./apim:/home/wso2carbon/wso2-config-volume
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
  billing-engine:
    image: ajanthan/billing-engine:2.6.0
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "8080"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
      api-manager:
        condition: service_healthy
    environment:
      - VerifyHostname=false
    volumes:
      - ./billing-engine/client-truststore.jks:/usr/local/tomcat/client-truststore.jks
      - ./billing-engine/datasource.properties:/usr/local/tomcat/webapps/apim-billing-engine-1.4.0/WEB-INF/classes/datasource.properties
    ports:
      - "8080:8080"
